language: python

cache:
  directories:
  - /opt/shellcheck
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

python:
- 3.6
- 3.7
- 3.8

matrix:
  include:
  - python: 3.6
  - python: 3.7
  - python: 3.8

before_install:
- export scversion="stable" # or "v0.4.7", or "latest"
- mkdir -p /opt/shellcheck
- "[[ ! -e /opt/shellcheck/shellcheck ]] && wget -qO- https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz
  | tar -xJv -O shellcheck-${scversion}/shellcheck | sudo tee /opt/shellcheck/shellcheck
  > /dev/null || true"
- sudo chmod +x /opt/shellcheck/shellcheck
- "/opt/shellcheck/shellcheck --version"
- export PATH="/opt/shellcheck:${PATH}"
- which -a shellcheck
- shellcheck --version

install:
- make init

script:
- make ci
