#!/usr/bin/env bash
# NB: the first regex removes colors from the output (https://stackoverflow.com/questions/17998978/removing-colors-from-output)
echo "$@" |
  python -c "import re;import sys;sys.stdout.write(re.sub(r'\\x1B\\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]', '', sys.stdin.read()))" |
  python -c 'import re, sys;sys.stdout.write(re.match(r"^\| (.*?)\s+\| ([^|]+?)\s+\|\s+([^|]+?)\s+\|$", sys.stdin.read()).group(1))'
